## Preprocessing

In [73]:
import pandas as pd
plays = pd.read_csv('pbp.csv')

plays.head()

,sequence_id,game_id,period,play_clock,home_description,away_description,score,player1_id,player1_name,player1_team,player2_id,player2_name,player2_team,player3_id,player3_name,player3_team,event_type,event_description
0,0,21500001,4,12:00,NaN,NaN,82 - 66,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,Start Period,NaN
1,1,21500001,4,11:44,NaN,Baynes Dunk (2 PTS) (Ilyasova 3 AST),84 - 66,203382,Aron Baynes,DET,101141,Ersan Ilyasova,DET,0,NaN,NaN,Made Shot,NaN
2,2,21500001,4,11:29,Schroder 2' Driving Finger Roll Layup (16 PTS),NaN,84 - 68,203471,Dennis Schroder,ATL,0,NaN,NaN,0,NaN,NaN,Made Shot,NaN
3,3,21500001,4,11:17,Schroder STEAL (2 STL),Blake Lost Ball Turnover (P3.T13),NaN,2581,Steve Blake,DET,203471,Dennis Schroder,ATL,0,NaN,NaN,Turnover,Lost Ball
4,4,21500001,4,11:14,NaN,Ilyasova S.FOUL (P3.T1) (Z.Zarba),NaN,101141,Ersan Ilyasova,DET,203471,Dennis Schroder,ATL,0,NaN,NaN,Foul,Shooting

'82 '

#### Fill in scores for non-scoring plays

In [75]:
plays['score'] = plays['score'].fillna(method='ffill')

,sequence_id,game_id,period,play_clock,home_description,away_description,score,player1_id,player1_name,player1_team,player2_id,player2_name,player2_team,player3_id,player3_name,player3_team,event_type,event_description
0,0,21500001,4,12:00,NaN,NaN,82 - 66,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,Start Period,NaN
1,1,21500001,4,11:44,NaN,Baynes Dunk (2 PTS) (Ilyasova 3 AST),84 - 66,203382,Aron Baynes,DET,101141,Ersan Ilyasova,DET,0,NaN,NaN,Made Shot,NaN
2,2,21500001,4,11:29,Schroder 2' Driving Finger Roll Layup (16 PTS),NaN,84 - 68,203471,Dennis Schroder,ATL,0,NaN,NaN,0,NaN,NaN,Made Shot,NaN
3,3,21500001,4,11:17,Schroder STEAL (2 STL),Blake Lost Ball Turnover (P3.T13),84 - 68,2581,Steve Blake,DET,203471,Dennis Schroder,ATL,0,NaN,NaN,Turnover,Lost Ball
4,4,21500001,4,11:14,NaN,Ilyasova S.FOUL (P3.T1) (Z.Zarba),84 - 68,101141,Ersan Ilyasova,DET,203471,Dennis Schroder,ATL,0,NaN,NaN,Foul,Shooting

#### Insert column for score difference

In [109]:
def score_difference(score):
    i = 0
    while score[i] != ' ':
        i += 1
    score_away = int(score[:i])

    i+=3
    score_home = int(score[i:])
    score_difference = score_home - score_away
    return score_difference


plays['score_difference'] = plays['score'].apply(lambda score: score_difference(score))

In [110]:
plays.head()

,sequence_id,game_id,period,play_clock,home_description,away_description,score,player1_id,player1_name,player1_team,...,player3_name,player3_team,event_type,event_description,possession,seconds_remaining,player1_lastname,player2_lastname,player3_lastname,score_difference
0,0,21500001,4,12:00,NaN,NaN,82 - 66,0,NaN,NaN,...,NaN,NaN,Start Period,NaN,0,720,NaN,NaN,NaN,-16
1,1,21500001,4,11:44,NaN,Baynes Dunk (2 PTS) (Ilyasova 3 AST),84 - 66,203382,Aron Baynes,DET,...,NaN,NaN,Made Shot,NaN,1,704,Baynes,Ilyasova,NaN,-18
2,2,21500001,4,11:29,Schroder 2' Driving Finger Roll Layup (16 PTS),NaN,84 - 68,203471,Dennis Schroder,ATL,...,NaN,NaN,Made Shot,NaN,0,689,Schroder,NaN,NaN,-16
3,3,21500001,4,11:17,Schroder STEAL (2 STL),Blake Lost Ball Turnover (P3.T13),84 - 68,2581,Steve Blake,DET,...,NaN,NaN,Turnover,Lost Ball,1,677,Blake,Schroder,NaN,-16
4,4,21500001,4,11:14,NaN,Ilyasova S.FOUL (P3.T1) (Z.Zarba),84 - 68,101141,Ersan Ilyasova,DET,...,NaN,NaN,Foul,Shooting,1,674,Ilyasova,Schroder,NaN,-16

#### Insert column for seconds remaining

In [69]:
def seconds_left(play_clock):
    i = 0
    while play_clock[i] != ':':
        i += 1
    minutes = int(play_clock[:i])
    i+=1
    seconds = int(play_clock[i:])
    
    seconds_left = 60*minutes + seconds
    return seconds_left

In [77]:
plays['seconds_remaining'] = plays['play_clock'].apply(lambda play_clock: seconds_left(play_clock))
plays.head()

,sequence_id,game_id,period,play_clock,home_description,away_description,score,player1_id,player1_name,player1_team,player2_id,player2_name,player2_team,player3_id,player3_name,player3_team,event_type,event_description,possession,seconds_remaining
0,0,21500001,4,12:00,NaN,NaN,82 - 66,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,Start Period,NaN,NaN,720
1,1,21500001,4,11:44,NaN,Baynes Dunk (2 PTS) (Ilyasova 3 AST),84 - 66,203382,Aron Baynes,DET,101141,Ersan Ilyasova,DET,0,NaN,NaN,Made Shot,NaN,NaN,704
2,2,21500001,4,11:29,Schroder 2' Driving Finger Roll Layup (16 PTS),NaN,84 - 68,203471,Dennis Schroder,ATL,0,NaN,NaN,0,NaN,NaN,Made Shot,NaN,NaN,689
3,3,21500001,4,11:17,Schroder STEAL (2 STL),Blake Lost Ball Turnover (P3.T13),84 - 68,2581,Steve Blake,DET,203471,Dennis Schroder,ATL,0,NaN,NaN,Turnover,Lost Ball,NaN,677
4,4,21500001,4,11:14,NaN,Ilyasova S.FOUL (P3.T1) (Z.Zarba),84 - 68,101141,Ersan Ilyasova,DET,203471,Dennis Schroder,ATL,0,NaN,NaN,Foul,Shooting,NaN,674

#### Extract player last names

In [91]:
import numpy as np

def last_name(name):
    if name is not np.nan:
        i = 0
        if name == "Nene":
            return name
        while name[i] != " ":
            i += 1
        i += 1
        return name[i:]
    else:
        return np.nan


plays['player1_lastname'] = plays['player1_name'].apply(lambda name: last_name(name))
plays['player2_lastname'] = plays['player2_name'].apply(lambda name: last_name(name))
plays['player3_lastname'] = plays['player3_name'].apply(lambda name: last_name(name))
plays.head()

,sequence_id,game_id,period,play_clock,home_description,away_description,score,player1_id,player1_name,player1_team,...,player3_id,player3_name,player3_team,event_type,event_description,possession,seconds_remaining,player1_lastname,player2_lastname,player3_lastname
0,0,21500001,4,12:00,NaN,NaN,82 - 66,0,NaN,NaN,...,0,NaN,NaN,Start Period,NaN,0,720,NaN,NaN,NaN
1,1,21500001,4,11:44,NaN,Baynes Dunk (2 PTS) (Ilyasova 3 AST),84 - 66,203382,Aron Baynes,DET,...,0,NaN,NaN,Made Shot,NaN,0,704,Baynes,Ilyasova,NaN
2,2,21500001,4,11:29,Schroder 2' Driving Finger Roll Layup (16 PTS),NaN,84 - 68,203471,Dennis Schroder,ATL,...,0,NaN,NaN,Made Shot,NaN,0,689,Schroder,NaN,NaN
3,3,21500001,4,11:17,Schroder STEAL (2 STL),Blake Lost Ball Turnover (P3.T13),84 - 68,2581,Steve Blake,DET,...,0,NaN,NaN,Turnover,Lost Ball,0,677,Blake,Schroder,NaN
4,4,21500001,4,11:14,NaN,Ilyasova S.FOUL (P3.T1) (Z.Zarba),84 - 68,101141,Ersan Ilyasova,DET,...,0,NaN,NaN,Foul,Shooting,0,674,Ilyasova,Schroder,NaN

#### Replace team names with "Home" or "Away"

In [124]:
def play_lastname(play):
    i = 0
    while play[i] != " ":
        i += 1
    return play[:i]

def home_or_away1(row):
    home_lastname = ""
    away_lastname = ""
    
    if not pd.isnull(row['home_description']):
        home_lastname = play_lastname(row['home_description'])
    
    if not pd.isnull(row['away_description']):
        away_lastname = play_lastname(row['away_description'])
    if pd.isnull(row['player1_lastname']):
        return "None"
    elif row['player1_lastname'] == home_lastname:
        return "Home"
    elif row['player1_lastname'] == away_lastname:
        return "Away"
    else:
        return "None"
    
def home_or_away2(row):
    home_lastname = ""
    away_lastname = ""
    if not pd.isnull(row['home_description']):
        home_lastname = play_lastname(row['home_description'])
    
    if not pd.isnull(row['away_description']):
        away_lastname = play_lastname(row['away_description'])
    if pd.isnull(row['player2_lastname']):
        return "None"
    elif row['player2_lastname'] == home_lastname:
        return "Home"
    elif row['player2_lastname'] == away_lastname:
        return "Away"
    else:
        return "None"
    
def home_or_away3(row):
    home_lastname = ""
    away_lastname = ""
    if not pd.isnull(row['home_description']):
        home_lastname = play_lastname(row['home_description'])
    
    if not pd.isnull(row['away_description']):
        away_lastname = play_lastname(row['away_description'])
    if pd.isnull(row['player3_lastname']):
        return "None"
    elif row['player3_lastname'] == home_lastname:
        return "Home"
    elif row['player3_lastname'] == away_lastname:
        return "Away"
    else:
        return "None"
    
    
plays['player1_team'] = plays.apply(lambda row1: home_or_away1(row1), axis=1)
plays['player2_team'] = plays.apply(lambda row2: home_or_away2(row2), axis=1)
plays['player3_team'] = plays.apply(lambda row3: home_or_away3(row3), axis=1)

In [129]:
plays.head()

,sequence_id,game_id,period,play_clock,home_description,away_description,score,player1_id,player1_name,player1_team,...,player3_name,player3_team,event_type,event_description,possession,seconds_remaining,player1_lastname,player2_lastname,player3_lastname,score_difference
0,0,21500001,4,12:00,NaN,NaN,82 - 66,0,NaN,None,...,NaN,None,Start Period,NaN,0,720,NaN,NaN,NaN,-16
1,1,21500001,4,11:44,NaN,Baynes Dunk (2 PTS) (Ilyasova 3 AST),84 - 66,203382,Aron Baynes,Away,...,NaN,None,Made Shot,NaN,1,704,Baynes,Ilyasova,NaN,-18
2,2,21500001,4,11:29,Schroder 2' Driving Finger Roll Layup (16 PTS),NaN,84 - 68,203471,Dennis Schroder,Home,...,NaN,None,Made Shot,NaN,0,689,Schroder,NaN,NaN,-16
3,3,21500001,4,11:17,Schroder STEAL (2 STL),Blake Lost Ball Turnover (P3.T13),84 - 68,2581,Steve Blake,Away,...,NaN,None,Turnover,Lost Ball,1,677,Blake,Schroder,NaN,-16
4,4,21500001,4,11:14,NaN,Ilyasova S.FOUL (P3.T1) (Z.Zarba),84 - 68,101141,Ersan Ilyasova,Away,...,NaN,None,Foul,Shooting,1,674,Ilyasova,Schroder,NaN,-16

#### Function for determining if home team has possession of the ball

In [106]:
## Returns 1 if the home team has the ball after the play, 0 otherwise
def possession(row):
    if row['event_type'] == "Start Period ":
        return 0
    elif row['event_type'] == "Made Shot ":
        if pd.isnull(row['home_description']):
            return 1
        else:
            return 0
    elif row['event_type'] == "Foul ":
        if pd.isnull(row['home_description']): ## if they did not commit the foul
            return 1
        else:
            return 0
    elif row['event_type'] == "Free Throw ":
        if row['event_description'] == "Free Throw 1 of 1" or row['event_description'] == "Free Throw 2 of 2" or row['event_description'] == "Free Throw 3 of 3":
            if pd.isnull(row['home_description']):
                return 1
            else:
                return 0
        else:
            if pd.isnull(row['home_description']):
                return 0
            else:
                return 1
    elif row['event_type'] == "Rebound ": ## if the home team is not listed as the rebounder, they do not have the ball
        if pd.isnull(row['home_description']):
            return 0
        else:
            return 1
    elif row['event_type'] == "Turnover ": 
        if pd.isnull(row['home_description']):
            return 1
        else:
            if "Turnover" in row['home_description']:
                return 0
            else:
                return 1
    elif row['event_type'] == "Violation ":
        if pd.isnull(row['home_description']):
            return 1
        else:
            return 0
    else: 
        return np.nan
    

plays['possession'] = plays.apply(possession, axis=1)

,sequence_id,game_id,period,play_clock,home_description,away_description,score,player1_id,player1_name,player1_team,...,player3_id,player3_name,player3_team,event_type,event_description,possession,seconds_remaining,player1_lastname,player2_lastname,player3_lastname
0,0,21500001,4,12:00,NaN,NaN,82 - 66,0,NaN,NaN,...,0,NaN,NaN,Start Period,NaN,0.0,720,NaN,NaN,NaN
1,1,21500001,4,11:44,NaN,Baynes Dunk (2 PTS) (Ilyasova 3 AST),84 - 66,203382,Aron Baynes,DET,...,0,NaN,NaN,Made Shot,NaN,1.0,704,Baynes,Ilyasova,NaN
2,2,21500001,4,11:29,Schroder 2' Driving Finger Roll Layup (16 PTS),NaN,84 - 68,203471,Dennis Schroder,ATL,...,0,NaN,NaN,Made Shot,NaN,0.0,689,Schroder,NaN,NaN
3,3,21500001,4,11:17,Schroder STEAL (2 STL),Blake Lost Ball Turnover (P3.T13),84 - 68,2581,Steve Blake,DET,...,0,NaN,NaN,Turnover,Lost Ball,1.0,677,Blake,Schroder,NaN
4,4,21500001,4,11:14,NaN,Ilyasova S.FOUL (P3.T1) (Z.Zarba),84 - 68,101141,Ersan Ilyasova,DET,...,0,NaN,NaN,Foul,Shooting,1.0,674,Ilyasova,Schroder,NaN

#### Fill in NaN possession values with forward fill

In [131]:
plays['possession'] = plays['possession'].fillna(method='ffill')
plays['possession'] = plays['possession'].astype(int)

In [140]:
plays.head()

,sequence_id,game_id,period,play_clock,home_description,away_description,score,player1_id,player1_name,player1_team,...,player3_team,event_type,event_description,possession,seconds_remaining,player1_lastname,player2_lastname,player3_lastname,score_difference,game_result
0,0,21500001,4,12:00,NaN,NaN,82 - 66,0,NaN,None,...,None,Start Period,NaN,0,720,NaN,NaN,NaN,-16,NaN
1,1,21500001,4,11:44,NaN,Baynes Dunk (2 PTS) (Ilyasova 3 AST),84 - 66,203382,Aron Baynes,Away,...,None,Made Shot,NaN,1,704,Baynes,Ilyasova,NaN,-18,NaN
2,2,21500001,4,11:29,Schroder 2' Driving Finger Roll Layup (16 PTS),NaN,84 - 68,203471,Dennis Schroder,Home,...,None,Made Shot,NaN,0,689,Schroder,NaN,NaN,-16,NaN
3,3,21500001,4,11:17,Schroder STEAL (2 STL),Blake Lost Ball Turnover (P3.T13),84 - 68,2581,Steve Blake,Away,...,None,Turnover,Lost Ball,1,677,Blake,Schroder,NaN,-16,NaN
4,4,21500001,4,11:14,NaN,Ilyasova S.FOUL (P3.T1) (Z.Zarba),84 - 68,101141,Ersan Ilyasova,Away,...,None,Foul,Shooting,1,674,Ilyasova,Schroder,NaN,-16,NaN

#### Accounting for star players

Every fan knows the star impact is bigger in basketball than any other sport. A star player's absence or presence on the court is felt, and we hypothesize that this transforms to significant differences in win probability. Thus, we keep a list of the top 25 players in the NBA, and keep track of how many star players each team has on the court after any play.

In [169]:
## player_id for the 25 star players of the NBA

star_ids = [202681,2546,162157,201188,203081,201599,202691,201143,202322,202710,200794,200768,203110,202326,200746,201933,202331,203076,201935,202695,201566,101108,201939,201142,2544]

In [177]:
all_home_stars = [[]]
all_away_stars = [[]]

home_stars = []
away_stars = []

i = 1
while i < 294366:
    if plays.iloc[i]['game_id'] != plays.iloc[i-1]['game_id']:
        home_stars = []
        away_stars = []
        i += 1
        all_home_stars.append(home_stars)
        all_away_stars.append(away_stars)
    else:
        if plays.iloc[i]['player1_team'] == "Home":
            if plays.iloc[i]['player1_id'] in star_ids:
                if plays.iloc[i]['event_type'] == 'Susbtitution ':
                    home_stars.remove(plays.iloc[i]['player1_id'])
                else:
                    if plays.iloc[i]['player1_id'] not in home_stars:
                        home_stars.append(plays.iloc[i]['player1_id'])
        if plays.iloc[i]['player2_team'] == "Home":
            if plays.iloc[i]['player2_id'] in star_ids:
                if plays.iloc[i]['event_type'] == 'Susbtitution ':
                    home_stars.append(plays.iloc[i]['player2_id'])
                else:
                    if plays.iloc[i]['player2_id'] not in home_stars:
                        home_stars.append(plays.iloc[i]['player2_id'])

        if plays.iloc[i]['player3_team'] == "Home":
            if plays.iloc[i]['player3_id'] in star_ids:
                if plays.iloc[i]['player3_id'] not in home_stars:
                    home_stars.append(plays.iloc[i]['player3_id'])
                        
                        
                        
        if plays.iloc[i]['player1_team'] == "Away":
            if plays.iloc[i]['player1_id'] in star_ids:
                if plays.iloc[i]['event_type'] == 'Susbtitution ':
                    away_stars.remove(plays.iloc[i]['player1_id'])
                else:
                    if plays.iloc[i]['player1_id'] not in away_stars:
                        away_stars.append(plays.iloc[i]['player1_id'])
        if plays.iloc[i]['player2_team'] == "Away":
            if plays.iloc[i]['player2_id'] in star_ids:
                if plays.iloc[i]['event_type'] == 'Susbtitution ':
                    away_stars.append(plays.iloc[i]['player2_id'])
                else:
                    if plays.iloc[i]['player2_id'] not in away_stars:
                        away_stars.append(plays.iloc[i]['player2_id'])

        if plays.iloc[i]['player3_team'] == "Away":
            if plays.iloc[i]['player3_id'] in star_ids:
                if plays.iloc[i]['player3_id'] not in away_stars:
                    away_stars.append(plays.iloc[i]['player3_id'])
                        
        all_home_stars.append(home_stars)
        all_away_stars.append(away_stars)
        i += 1

In [178]:
plays['home_stars'] = all_home_stars
plays['away_stars'] = all_away_stars

In [179]:
plays['num_home_stars'] = plays.apply(lambda row: len(row['home_stars']), axis=1)
plays['num_away_stars'] = plays.apply(lambda row: len(row['away_stars']), axis=1)
plays.head()

,sequence_id,game_id,period,play_clock,home_description,away_description,score,player1_id,player1_name,player1_team,...,seconds_remaining,player1_lastname,player2_lastname,player3_lastname,score_difference,game_result,home_stars,away_stars,num_home_stars,num_away_stars
0,0,21500001,4,12:00,NaN,NaN,82 - 66,0,NaN,None,...,720,NaN,NaN,NaN,-16,0,[],[],0,0
1,1,21500001,4,11:44,NaN,Baynes Dunk (2 PTS) (Ilyasova 3 AST),84 - 66,203382,Aron Baynes,Away,...,704,Baynes,Ilyasova,NaN,-18,0,"[201143, 200794]",[],2,0
2,2,21500001,4,11:29,Schroder 2' Driving Finger Roll Layup (16 PTS),NaN,84 - 68,203471,Dennis Schroder,Home,...,689,Schroder,NaN,NaN,-16,0,"[201143, 200794]",[],2,0
3,3,21500001,4,11:17,Schroder STEAL (2 STL),Blake Lost Ball Turnover (P3.T13),84 - 68,2581,Steve Blake,Away,...,677,Blake,Schroder,NaN,-16,0,"[201143, 200794]",[],2,0
4,4,21500001,4,11:14,NaN,Ilyasova S.FOUL (P3.T1) (Z.Zarba),84 - 68,101141,Ersan Ilyasova,Away,...,674,Ilyasova,Schroder,NaN,-16,0,"[201143, 200794]",[],2,0

In [176]:
l = [[]]
l.append([])
l

[[], []]

#### Adding column for whether game was won or not

In [170]:
def result(row):
    if row['event_type'] == "End Period ":
        if row['score_difference'] < 0:
            return 0
        elif row['score_difference'] > 0:
            return 1
    return np.nan

plays['game_result'] = plays.apply(result,axis=1)
plays['game_result'] = plays['game_result'].fillna(method='bfill')
plays['game_result'] = plays['game_result'].astype(int)

In [172]:
plays.to_csv('pbp_model_data.csv')

0.8713879999728229

0.58131373867905944

Number of observations in the training data: 220774
Number of observations in the test data: 73592

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

,sequence_id,game_id,period,play_clock,home_description,away_description,score,player1_id,player1_name,player1_team,...,player2_lastname,player3_lastname,score_difference,game_result,home_stars,away_stars,num_home_stars,num_away_stars,is_train,win_prob
2,2,21500001,4,11:29,Schroder 2' Driving Finger Roll Layup (16 PTS),NaN,84 - 68,203471,Dennis Schroder,Home,...,NaN,NaN,-16,0,"[201143, 200794]",[],2,0,False,1.0
3,3,21500001,4,11:17,Schroder STEAL (2 STL),Blake Lost Ball Turnover (P3.T13),84 - 68,2581,Steve Blake,Away,...,Schroder,NaN,-16,0,"[201143, 200794]",[],2,0,False,1.0
5,5,21500001,4,11:14,Schroder Free Throw 1 of 2 (17 PTS),NaN,84 - 69,203471,Dennis Schroder,Home,...,NaN,NaN,-15,0,"[201143, 200794]",[],2,0,False,1.0
15,15,21500001,4,10:16,Muscala Foul Turnover (P1.T14),NaN,86 - 70,203488,Mike Muscala,Home,...,NaN,NaN,-16,0,"[201143, 200794]",[],2,0,False,1.0
21,21,21500001,4,9:41,NaN,Meeks 1' Driving Layup (2 PTS) (Blake 3 AST),88 - 70,201975,Jodie Meeks,Away,...,Blake,NaN,-18,0,"[201143, 200794]",[],2,0,False,1.0